//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class En {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal En() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataRepository.En", typeof(En).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Balance is not enough 的本地化字符串。
        /// </summary>
        internal static string AccountBalanceNotEnough {
            get {
                return ResourceManager.GetString("AccountBalanceNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account has been frozen, please contact the administrator. 的本地化字符串。
        /// </summary>
        internal static string AccountIsFreezing {
            get {
                return ResourceManager.GetString("AccountIsFreezing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account has been locked, please contact the administrator. 的本地化字符串。
        /// </summary>
        internal static string AccountIsLocking {
            get {
                return ResourceManager.GetString("AccountIsLocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account has been sealed, please contact the administrator. 的本地化字符串。
        /// </summary>
        internal static string AccountIsSealUp {
            get {
                return ResourceManager.GetString("AccountIsSealUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account has not been activated, temporarily unable to log on. 的本地化字符串。
        /// </summary>
        internal static string AccountIsUnActived {
            get {
                return ResourceManager.GetString("AccountIsUnActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Amount can not be empty. 的本地化字符串。
        /// </summary>
        internal static string AmountCanNotBeEmpty {
            get {
                return ResourceManager.GetString("AmountCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The amount can only be an integral multiple of 50 的本地化字符串。
        /// </summary>
        internal static string AmountTypeError {
            get {
                return ResourceManager.GetString("AmountTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auth failed,please login again. 的本地化字符串。
        /// </summary>
        internal static string AuthFailed {
            get {
                return ResourceManager.GetString("AuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The bankcard number code can not be empty. 的本地化字符串。
        /// </summary>
        internal static string BankcardNoCanNotBeEmpty {
            get {
                return ResourceManager.GetString("BankcardNoCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The bank name code can not be empty. 的本地化字符串。
        /// </summary>
        internal static string BankNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("BankNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Business hours are from 6:00 to 23:00. 的本地化字符串。
        /// </summary>
        internal static string BusinessHoursError {
            get {
                return ResourceManager.GetString("BusinessHoursError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current number of purchase times reaches the upper limit. 的本地化字符串。
        /// </summary>
        internal static string CurrentToBuyTimeLimit {
            get {
                return ResourceManager.GetString("CurrentToBuyTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of letters per day reaches the upper limit. 的本地化字符串。
        /// </summary>
        internal static string DailyMessageboardCountLimit {
            get {
                return ResourceManager.GetString("DailyMessageboardCountLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dangerous content 的本地化字符串。
        /// </summary>
        internal static string DangerousContent {
            get {
                return ResourceManager.GetString("DangerousContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of equipment reaches the upper limit. 的本地化字符串。
        /// </summary>
        internal static string EquipmentCountLimit {
            get {
                return ResourceManager.GetString("EquipmentCountLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It&apos;s gone beyond recall. 的本地化字符串。
        /// </summary>
        internal static string ErrorCancelStatus {
            get {
                return ResourceManager.GetString("ErrorCancelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid number 的本地化字符串。
        /// </summary>
        internal static string ErrorId {
            get {
                return ResourceManager.GetString("ErrorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Inviting relationship 的本地化字符串。
        /// </summary>
        internal static string ErrorInvitRelationship {
            get {
                return ResourceManager.GetString("ErrorInvitRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid username or password! 的本地化字符串。
        /// </summary>
        internal static string ErrorUserNameOrPassword {
            get {
                return ResourceManager.GetString("ErrorUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error value type 的本地化字符串。
        /// </summary>
        internal static string ErrorValueType {
            get {
                return ResourceManager.GetString("ErrorValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum number of giving times 的本地化字符串。
        /// </summary>
        internal static string GiveTimeLimit {
            get {
                return ResourceManager.GetString("GiveTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The international code can not be empty. 的本地化字符串。
        /// </summary>
        internal static string GlobalAreaCodeCanNotBeEmpty {
            get {
                return ResourceManager.GetString("GlobalAreaCodeCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid verification code 的本地化字符串。
        /// </summary>
        internal static string InvalidVerificationCode {
            get {
                return ResourceManager.GetString("InvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inviter balance is not enough 的本地化字符串。
        /// </summary>
        internal static string InviterAccountBalanceNotEnough {
            get {
                return ResourceManager.GetString("InviterAccountBalanceNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inviter is not existed 的本地化字符串。
        /// </summary>
        internal static string InviterError {
            get {
                return ResourceManager.GetString("InviterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logic Error 的本地化字符串。
        /// </summary>
        internal static string LogicError {
            get {
                return ResourceManager.GetString("LogicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment can not be collected,because of error status. 的本地化字符串。
        /// </summary>
        internal static string MiningEquipmentCollectError {
            get {
                return ResourceManager.GetString("MiningEquipmentCollectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password can not be empty. 的本地化字符串。
        /// </summary>
        internal static string MobileCanNotBeEmpty {
            get {
                return ResourceManager.GetString("MobileCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mobile is existed 的本地化字符串。
        /// </summary>
        internal static string MobileIsExisted {
            get {
                return ResourceManager.GetString("MobileIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The phone number is not correct. 的本地化字符串。
        /// </summary>
        internal static string MobileRegexError {
            get {
                return ResourceManager.GetString("MobileRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is necessary to purchase mining equipment before purchasing. 的本地化字符串。
        /// </summary>
        internal static string MustBuyMiningEquipment {
            get {
                return ResourceManager.GetString("MustBuyMiningEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password can not be empty. 的本地化字符串。
        /// </summary>
        internal static string PasswordCanNotBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The password and confirmation password do not match. 的本地化字符串。
        /// </summary>
        internal static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passwords with a length of 6-20 bits and uppercase letters must contain uppercase letters, lowercase letters and digits. 的本地化字符串。
        /// </summary>
        internal static string PasswordRegexError {
            get {
                return ResourceManager.GetString("PasswordRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid parameters 的本地化字符串。
        /// </summary>
        internal static string PropertyNameInvalid {
            get {
                return ResourceManager.GetString("PropertyNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Has refined today 的本地化字符串。
        /// </summary>
        internal static string RefiningTooBusy {
            get {
                return ResourceManager.GetString("RefiningTooBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stay out of business 的本地化字符串。
        /// </summary>
        internal static string SundayToRest {
            get {
                return ResourceManager.GetString("SundayToRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System is error now ,please try it later! 的本地化字符串。
        /// </summary>
        internal static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The purchase times
        /// reaches the upper limit. 的本地化字符串。
        /// </summary>
        internal static string ToBuyTimeLimit {
            get {
                return ResourceManager.GetString("ToBuyTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid buyer 的本地化字符串。
        /// </summary>
        internal static string TransferBillFromMemberError {
            get {
                return ResourceManager.GetString("TransferBillFromMemberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid trade status 的本地化字符串。
        /// </summary>
        internal static string TransferBillStatusError {
            get {
                return ResourceManager.GetString("TransferBillStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid seller 的本地化字符串。
        /// </summary>
        internal static string TransferBillToMemberError {
            get {
                return ResourceManager.GetString("TransferBillToMemberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid trading type 的本地化字符串。
        /// </summary>
        internal static string TransferBillTypeError {
            get {
                return ResourceManager.GetString("TransferBillTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account has been activated 的本地化字符串。
        /// </summary>
        internal static string UserIsActived {
            get {
                return ResourceManager.GetString("UserIsActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username can not be empty. 的本地化字符串。
        /// </summary>
        internal static string UserNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("UserNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username is existed 的本地化字符串。
        /// </summary>
        internal static string UserNameIsExisted {
            get {
                return ResourceManager.GetString("UserNameIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username is not existed 的本地化字符串。
        /// </summary>
        internal static string UserNameIsNotExisted {
            get {
                return ResourceManager.GetString("UserNameIsNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid username or name! 的本地化字符串。
        /// </summary>
        internal static string UserNameIsNotMatchName {
            get {
                return ResourceManager.GetString("UserNameIsNotMatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of the user name is 6-20 digit, upper case and lowercase letter. 的本地化字符串。
        /// </summary>
        internal static string UserNameLengthError {
            get {
                return ResourceManager.GetString("UserNameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification code error 的本地化字符串。
        /// </summary>
        internal static string VerifyCodeError {
            get {
                return ResourceManager.GetString("VerifyCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wallet can not be empty. 的本地化字符串。
        /// </summary>
        internal static string WalletCanNotBeEmpty {
            get {
                return ResourceManager.GetString("WalletCanNotBeEmpty", resourceCulture);
            }
        }
    }
}
