//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRepository {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ZhCn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ZhCn() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataRepository.ZhCn", typeof(ZhCn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 账户余额不足 的本地化字符串。
        /// </summary>
        public static string AccountBalanceNotEnough {
            get {
                return ResourceManager.GetString("AccountBalanceNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号已冻结，请联系管理人员 的本地化字符串。
        /// </summary>
        public static string AccountIsFreezing {
            get {
                return ResourceManager.GetString("AccountIsFreezing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号已锁定，请联系管理人员 的本地化字符串。
        /// </summary>
        public static string AccountIsLocking {
            get {
                return ResourceManager.GetString("AccountIsLocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号已查封，请联系管理人员 的本地化字符串。
        /// </summary>
        public static string AccountIsSealUp {
            get {
                return ResourceManager.GetString("AccountIsSealUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号还未激活，暂时无法登陆 的本地化字符串。
        /// </summary>
        public static string AccountIsUnActived {
            get {
                return ResourceManager.GetString("AccountIsUnActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入金额 的本地化字符串。
        /// </summary>
        public static string AmountCanNotBeEmpty {
            get {
                return ResourceManager.GetString("AmountCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金额只能是50的整数倍 的本地化字符串。
        /// </summary>
        public static string AmountTypeError {
            get {
                return ResourceManager.GetString("AmountTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权信息失败，请重新登录 的本地化字符串。
        /// </summary>
        public static string AuthFailed {
            get {
                return ResourceManager.GetString("AuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行卡号不能为空 的本地化字符串。
        /// </summary>
        public static string BankcardNoCanNotBeEmpty {
            get {
                return ResourceManager.GetString("BankcardNoCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行名称不能为空 的本地化字符串。
        /// </summary>
        public static string BankNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("BankNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 营业时间为每日6：00-23：00 的本地化字符串。
        /// </summary>
        public static string BusinessHoursError {
            get {
                return ResourceManager.GetString("BusinessHoursError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前求购次数达到上限 的本地化字符串。
        /// </summary>
        public static string CurrentToBuyTimeLimit {
            get {
                return ResourceManager.GetString("CurrentToBuyTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每日站内信数量达到上限 的本地化字符串。
        /// </summary>
        public static string DailyMessageboardCountLimit {
            get {
                return ResourceManager.GetString("DailyMessageboardCountLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 危险的提交内容 的本地化字符串。
        /// </summary>
        public static string DangerousContent {
            get {
                return ResourceManager.GetString("DangerousContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备数量达到上限 的本地化字符串。
        /// </summary>
        public static string EquipmentCountLimit {
            get {
                return ResourceManager.GetString("EquipmentCountLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该状态不能够取消 的本地化字符串。
        /// </summary>
        public static string ErrorCancelStatus {
            get {
                return ResourceManager.GetString("ErrorCancelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的编号 的本地化字符串。
        /// </summary>
        public static string ErrorId {
            get {
                return ResourceManager.GetString("ErrorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邀请关系有误 的本地化字符串。
        /// </summary>
        public static string ErrorInvitRelationship {
            get {
                return ResourceManager.GetString("ErrorInvitRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的用户名或者密码 的本地化字符串。
        /// </summary>
        public static string ErrorUserNameOrPassword {
            get {
                return ResourceManager.GetString("ErrorUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的值类型 的本地化字符串。
        /// </summary>
        public static string ErrorValueType {
            get {
                return ResourceManager.GetString("ErrorValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赠送次数达到上限 的本地化字符串。
        /// </summary>
        public static string GiveTimeLimit {
            get {
                return ResourceManager.GetString("GiveTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国际区号不能为空 的本地化字符串。
        /// </summary>
        public static string GlobalAreaCodeCanNotBeEmpty {
            get {
                return ResourceManager.GetString("GlobalAreaCodeCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码错误 的本地化字符串。
        /// </summary>
        public static string InvalidVerificationCode {
            get {
                return ResourceManager.GetString("InvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邀请人账户余额不足 的本地化字符串。
        /// </summary>
        public static string InviterAccountBalanceNotEnough {
            get {
                return ResourceManager.GetString("InviterAccountBalanceNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邀请用户信息错误 的本地化字符串。
        /// </summary>
        public static string InviterError {
            get {
                return ResourceManager.GetString("InviterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务逻辑错误 的本地化字符串。
        /// </summary>
        public static string LogicError {
            get {
                return ResourceManager.GetString("LogicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该设备还不能收取 的本地化字符串。
        /// </summary>
        public static string MiningEquipmentCollectError {
            get {
                return ResourceManager.GetString("MiningEquipmentCollectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号不能缺少 的本地化字符串。
        /// </summary>
        public static string MobileCanNotBeEmpty {
            get {
                return ResourceManager.GetString("MobileCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号已存在 的本地化字符串。
        /// </summary>
        public static string MobileIsExisted {
            get {
                return ResourceManager.GetString("MobileIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号格式不正确 的本地化字符串。
        /// </summary>
        public static string MobileRegexError {
            get {
                return ResourceManager.GetString("MobileRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须购买完采矿设备才可以发起求购 的本地化字符串。
        /// </summary>
        public static string MustBuyMiningEquipment {
            get {
                return ResourceManager.GetString("MustBuyMiningEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码 的本地化字符串。
        /// </summary>
        public static string PasswordCanNotBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码和确认密码不匹配 的本地化字符串。
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码长度为6-20位的数字和大小写字母,必须包含大写字母，小写字母和数字 的本地化字符串。
        /// </summary>
        public static string PasswordRegexError {
            get {
                return ResourceManager.GetString("PasswordRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数名不合法 的本地化字符串。
        /// </summary>
        public static string PropertyNameInvalid {
            get {
                return ResourceManager.GetString("PropertyNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一天只能精炼一次 的本地化字符串。
        /// </summary>
        public static string RefiningTooBusy {
            get {
                return ResourceManager.GetString("RefiningTooBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周日哦，休息中 的本地化字符串。
        /// </summary>
        public static string SundayToRest {
            get {
                return ResourceManager.GetString("SundayToRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器打了个盹~ 的本地化字符串。
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每日求购次数达到上限 的本地化字符串。
        /// </summary>
        public static string ToBuyTimeLimit {
            get {
                return ResourceManager.GetString("ToBuyTimeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易单买家信息不正确 的本地化字符串。
        /// </summary>
        public static string TransferBillFromMemberError {
            get {
                return ResourceManager.GetString("TransferBillFromMemberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易单状态错误 的本地化字符串。
        /// </summary>
        public static string TransferBillStatusError {
            get {
                return ResourceManager.GetString("TransferBillStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易单卖家信息不正确 的本地化字符串。
        /// </summary>
        public static string TransferBillToMemberError {
            get {
                return ResourceManager.GetString("TransferBillToMemberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易单类型不合法 的本地化字符串。
        /// </summary>
        public static string TransferBillTypeError {
            get {
                return ResourceManager.GetString("TransferBillTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已激活 的本地化字符串。
        /// </summary>
        public static string UserIsActived {
            get {
                return ResourceManager.GetString("UserIsActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户名 的本地化字符串。
        /// </summary>
        public static string UserNameCanNotBeEmpty {
            get {
                return ResourceManager.GetString("UserNameCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该用户名已存在 的本地化字符串。
        /// </summary>
        public static string UserNameIsExisted {
            get {
                return ResourceManager.GetString("UserNameIsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该用户名不存在 的本地化字符串。
        /// </summary>
        public static string UserNameIsNotExisted {
            get {
                return ResourceManager.GetString("UserNameIsNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号和姓名不匹配 的本地化字符串。
        /// </summary>
        public static string UserNameIsNotMatchName {
            get {
                return ResourceManager.GetString("UserNameIsNotMatchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名长度为6-20位的数字和大小写字母 的本地化字符串。
        /// </summary>
        public static string UserNameLengthError {
            get {
                return ResourceManager.GetString("UserNameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码错误 的本地化字符串。
        /// </summary>
        public static string VerifyCodeError {
            get {
                return ResourceManager.GetString("VerifyCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钱包不能为空 的本地化字符串。
        /// </summary>
        public static string WalletCanNotBeEmpty {
            get {
                return ResourceManager.GetString("WalletCanNotBeEmpty", resourceCulture);
            }
        }
    }
}
